apiVersion: v1
kind: ReplicationController
metadata:
  name: grocery-list-rc
spec:
  replicas: 2
  selector:
    app: grocery-list
  template:
    metadata:
      labels:
        app: grocery-list
    spec:
      containers:
      - name: grocery-list
        image: zmad5306/grocery-list-ng:latest
        ports:
        - containerPort: 80